spring.application.name=CoApp

spring.mongodb.uri=${SPRING_DATA_MONGODB_URI}

spring.config.import=optional:file:./local.properties

# Use the PORT env var if it exists (Render uses 10000), otherwise default to 8080 (for local)
server.port=${PORT:8080}