package com.backend.coapp.model.document;

import static org.junit.jupiter.api.Assertions.*;

import com.backend.coapp.util.ExperienceConstants;
import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import jakarta.validation.ValidatorFactory;
import java.time.LocalDate;
import java.util.Set;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.NullAndEmptySource;
import org.junit.jupiter.params.provider.ValueSource;

/** The test is generated by Claude and revised by Bao Ngo. */
class UserExperienceModelTest {
  private Validator validator;
  private final String VALID_ID = "fooUserId";
  private final String VALID_USER_ID = "fooUserId";
  private final String VALID_COMPANY_ID = "fooCompanyId";
  private final String VALID_ROLE_TITLE = "Foo role";
  private final String VALID_ROLE_DESCRIPTION = "Doing foo tasks: do nothing, sleeping";
  private final LocalDate VALID_START_DATE = LocalDate.now().minusYears(1);
  private final LocalDate VALID_END_DATE = LocalDate.now();

  @BeforeEach
  void setUp() {
    ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
    this.validator = factory.getValidator();
  }

  private UserExperienceModel buildValidModel() {
    return new UserExperienceModel(
        VALID_ID,
        VALID_USER_ID,
        VALID_COMPANY_ID,
        VALID_ROLE_TITLE,
        VALID_ROLE_DESCRIPTION,
        VALID_START_DATE,
        VALID_END_DATE);
  }

  private void assertHasViolation(UserExperienceModel model, String expectedMessage) {
    Set<ConstraintViolation<UserExperienceModel>> violations = validator.validate(model);
    assertTrue(
        violations.stream().anyMatch(v -> v.getMessage().equals(expectedMessage)),
        "Expected violation: " + expectedMessage);
  }

  private void assertNoViolations(UserExperienceModel model) {
    Set<ConstraintViolation<UserExperienceModel>> violations = validator.validate(model);
    assertTrue(violations.isEmpty(), "Expected no violations but got: " + violations);
  }

  @Test
  void model_whenAllFieldsValid_shouldPassValidation() {
    assertNoViolations(buildValidModel());
  }

  @Test
  void model_whenEndDateIsNull_shouldPassValidation() {
    UserExperienceModel model = buildValidModel();
    model.setEndDate(null); // current job, endDate is optional
    assertNoViolations(model);
  }

  @ParameterizedTest
  @NullAndEmptySource
  @ValueSource(strings = {"   "})
  void model_whenUserIdIsInvalid_shouldFailValidation(String userId) {
    UserExperienceModel model = buildValidModel();
    model.setUserId(userId);
    assertHasViolation(model, "User ID cannot be empty");
  }

  @ParameterizedTest
  @NullAndEmptySource
  @ValueSource(strings = {"   "})
  void model_whenCompanyIdIsInvalid_shouldFailValidation(String companyId) {
    UserExperienceModel model = buildValidModel();
    model.setCompanyId(companyId);
    assertHasViolation(model, "Company ID cannot be empty");
  }

  @Test
  void model_whenRoleDescriptionIsNull_shouldFailValidation() {
    UserExperienceModel model = buildValidModel();
    model.setRoleDescription(null);
    Set<ConstraintViolation<UserExperienceModel>> violations = validator.validate(model);
    assertFalse(violations.isEmpty());
  }

  @Test
  void model_whenRoleDescriptionIsBlank_shouldFailValidation() {
    UserExperienceModel model = buildValidModel();
    model.setRoleDescription("   ");
    Set<ConstraintViolation<UserExperienceModel>> violations = validator.validate(model);
    assertFalse(violations.isEmpty());
  }

  @Test
  void model_whenRoleDescriptionExceedsMaxLength_shouldFailValidation() {
    UserExperienceModel model = buildValidModel();
    model.setRoleDescription("a".repeat(ExperienceConstants.MAX_EXPERIENCE_DESCRIPTION_LENGTH + 1));
    assertHasViolation(
        model,
        "Experience description cannot exceed "
            + ExperienceConstants.MAX_EXPERIENCE_DESCRIPTION_LENGTH
            + " characters");
  }

  @Test
  void model_whenRoleDescriptionIsExactlyMaxLength_shouldPassValidation() {
    UserExperienceModel model = buildValidModel();
    model.setRoleDescription("a".repeat(ExperienceConstants.MAX_EXPERIENCE_DESCRIPTION_LENGTH));
    assertNoViolations(model);
  }

  @Test
  void model_whenStartDateIsNull_shouldFailValidation() {
    UserExperienceModel model = buildValidModel();
    model.setStartDate(null);
    Set<ConstraintViolation<UserExperienceModel>> violations = validator.validate(model);
    assertFalse(violations.isEmpty());
  }

  // --- roleTitle ---

  @ParameterizedTest
  @NullAndEmptySource
  @ValueSource(strings = {"   "})
  void model_whenRoleTitleIsNull_shouldFailValidation(String roleTitle) {
    UserExperienceModel model = buildValidModel();
    model.setRoleTitle(roleTitle);
    assertHasViolation(model, "Job title cannot be empty");
  }

  @Test
  void model_whenRoleTitleExceedsMaxLength_shouldFailValidation() {
    UserExperienceModel model = buildValidModel();
    model.setRoleTitle("a".repeat(ExperienceConstants.MAX_JOB_TITLE_LENGTH + 1));
    assertHasViolation(
        model,
        "Job title description cannot exceed "
            + ExperienceConstants.MAX_JOB_TITLE_LENGTH
            + " characters");
  }

  @Test
  void model_whenRoleTitleIsExactlyMaxLength_shouldPassValidation() {
    UserExperienceModel model = buildValidModel();
    model.setRoleTitle("a".repeat(ExperienceConstants.MAX_JOB_TITLE_LENGTH));
    assertNoViolations(model);
  }

  @Test
  void constructor_whenValidArgs_shouldSetFieldsCorrectly() {
    UserExperienceModel model =
        new UserExperienceModel(
            VALID_USER_ID,
            VALID_COMPANY_ID,
            VALID_ROLE_TITLE,
            VALID_ROLE_DESCRIPTION,
            VALID_START_DATE,
            VALID_END_DATE);

    assertEquals(VALID_USER_ID, model.getUserId());
    assertEquals(VALID_COMPANY_ID, model.getCompanyId());
    assertEquals(VALID_ROLE_TITLE, model.getRoleTitle());
    assertEquals(VALID_ROLE_DESCRIPTION, model.getRoleDescription());
    assertEquals(VALID_START_DATE, model.getStartDate());
    assertEquals(VALID_END_DATE, model.getEndDate());
    assertNull(model.getId()); // id should not be set
  }

  @Test
  void constructor_whenEndDateIsNull_shouldSetEndDateAsNull() {
    UserExperienceModel model =
        new UserExperienceModel(
            VALID_USER_ID,
            VALID_COMPANY_ID,
            VALID_ROLE_TITLE,
            VALID_ROLE_DESCRIPTION,
            VALID_START_DATE,
            null); // current job

    assertNull(model.getEndDate());
    assertNull(model.getId());
  }

  @Test
  void constructor_shouldNeverSetId() {
    UserExperienceModel model1 =
        new UserExperienceModel(
            VALID_USER_ID,
            VALID_COMPANY_ID,
            VALID_ROLE_TITLE,
            VALID_ROLE_DESCRIPTION,
            VALID_START_DATE,
            VALID_END_DATE);

    UserExperienceModel model2 =
        new UserExperienceModel(
            VALID_USER_ID,
            VALID_COMPANY_ID,
            VALID_ROLE_TITLE,
            VALID_ROLE_DESCRIPTION,
            VALID_START_DATE,
            null);

    assertNull(model1.getId());
    assertNull(model2.getId());
  }
}
