package com.backend.coapp.model.document;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.backend.coapp.util.ExperienceConstants;
import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import jakarta.validation.ValidatorFactory;
import java.time.LocalDate;
import java.util.Set;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/** The test is generated by Claude and revised by Bao Ngo. */
public class UserExperienceModelTest {
  private Validator validator;
  private final String VALID_ID = "fooUserId";
  private final String VALID_USER_ID = "fooUserId";
  private final String VALID_COMPANY_ID = "fooCompanyId";
  private final String VALID_ROLE_DESCRIPTION = "Foo role";
  private final LocalDate VALID_START_DATE = LocalDate.now().minusYears(1);
  private final LocalDate VALID_END_DATE = LocalDate.now();

  @BeforeEach
  public void setUp() {
    ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
    this.validator = factory.getValidator();
  }

  private UserExperienceModel buildValidModel() {
    return new UserExperienceModel(
        VALID_ID,
        VALID_USER_ID,
        VALID_COMPANY_ID,
        VALID_ROLE_DESCRIPTION,
        VALID_START_DATE,
        VALID_END_DATE);
  }

  private void assertHasViolation(UserExperienceModel model, String expectedMessage) {
    Set<ConstraintViolation<UserExperienceModel>> violations = validator.validate(model);
    assertTrue(
        violations.stream().anyMatch(v -> v.getMessage().equals(expectedMessage)),
        "Expected violation: " + expectedMessage);
  }

  private void assertNoViolations(UserExperienceModel model) {
    Set<ConstraintViolation<UserExperienceModel>> violations = validator.validate(model);
    assertTrue(violations.isEmpty(), "Expected no violations but got: " + violations);
  }

  @Test
  public void model_whenAllFieldsValid_shouldPassValidation() {
    assertNoViolations(buildValidModel());
  }

  @Test
  public void model_whenEndDateIsNull_shouldPassValidation() {
    UserExperienceModel model = buildValidModel();
    model.setEndDate(null); // current job, endDate is optional
    assertNoViolations(model);
  }

  @Test
  public void model_whenUserIdIsNull_shouldFailValidation() {
    UserExperienceModel model = buildValidModel();
    model.setUserId(null);
    assertHasViolation(model, "User ID cannot be empty");
  }

  @Test
  public void model_whenUserIdIsBlank_shouldFailValidation() {
    UserExperienceModel model = buildValidModel();
    model.setUserId("   ");
    assertHasViolation(model, "User ID cannot be empty");
  }

  @Test
  public void model_whenUserIdIsEmpty_shouldFailValidation() {
    UserExperienceModel model = buildValidModel();
    model.setUserId("");
    assertHasViolation(model, "User ID cannot be empty");
  }

  @Test
  public void model_whenCompanyIdIsNull_shouldFailValidation() {
    UserExperienceModel model = buildValidModel();
    model.setCompanyId(null);
    assertHasViolation(model, "Company ID cannot be empty");
  }

  @Test
  public void model_whenCompanyIdIsBlank_shouldFailValidation() {
    UserExperienceModel model = buildValidModel();
    model.setCompanyId("   ");
    assertHasViolation(model, "Company ID cannot be empty");
  }

  @Test
  public void model_whenCompanyIdIsEmpty_shouldFailValidation() {
    UserExperienceModel model = buildValidModel();
    model.setCompanyId("");
    assertHasViolation(model, "Company ID cannot be empty");
  }

  @Test
  public void model_whenRoleDescriptionIsNull_shouldFailValidation() {
    UserExperienceModel model = buildValidModel();
    model.setRoleDescription(null);
    Set<ConstraintViolation<UserExperienceModel>> violations = validator.validate(model);
    assertFalse(violations.isEmpty());
  }

  @Test
  public void model_whenRoleDescriptionIsBlank_shouldFailValidation() {
    UserExperienceModel model = buildValidModel();
    model.setRoleDescription("   ");
    Set<ConstraintViolation<UserExperienceModel>> violations = validator.validate(model);
    assertFalse(violations.isEmpty());
  }

  @Test
  public void model_whenRoleDescriptionExceedsMaxLength_shouldFailValidation() {
    UserExperienceModel model = buildValidModel();
    model.setRoleDescription("a".repeat(ExperienceConstants.MAX_EXPERIENCE_DESCRIPTION_LENGTH + 1));
    assertHasViolation(
        model,
        "Experience description cannot exceed "
            + ExperienceConstants.MAX_EXPERIENCE_DESCRIPTION_LENGTH
            + " characters");
  }

  @Test
  public void model_whenRoleDescriptionIsExactlyMaxLength_shouldPassValidation() {
    UserExperienceModel model = buildValidModel();
    model.setRoleDescription("a".repeat(ExperienceConstants.MAX_EXPERIENCE_DESCRIPTION_LENGTH));
    assertNoViolations(model);
  }

  @Test
  public void model_whenStartDateIsNull_shouldFailValidation() {
    UserExperienceModel model = buildValidModel();
    model.setStartDate(null);
    Set<ConstraintViolation<UserExperienceModel>> violations = validator.validate(model);
    assertFalse(violations.isEmpty());
  }
}
