package com.backend.coapp.model.document;

import static org.junit.jupiter.api.Assertions.*;

import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import jakarta.validation.ValidatorFactory;
import java.time.LocalDateTime;
import java.util.Set;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.NullAndEmptySource;
import org.junit.jupiter.params.provider.ValueSource;

/** The test is generated by Claude and revised by Bao Ngo. */
class UserGenAIUsageModelTest {

  private Validator validator;
  private final String VALID_ID = "fooId";
  private final String VALID_USER_ID = "fooUserId";
  private final int VALID_REQUEST_COUNT = 0;
  private final int VALID_MONTHLY_LIMIT = 100;
  private final LocalDateTime VALID_LAST_RESET = LocalDateTime.now();
  private final Long VALID_VERSION = 1L;

  @BeforeEach
  void setUp() {
    ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
    this.validator = factory.getValidator();
  }

  private UserGenAIUsageModel buildValidModel() {
    return new UserGenAIUsageModel(
        VALID_ID,
        VALID_USER_ID,
        VALID_REQUEST_COUNT,
        VALID_MONTHLY_LIMIT,
        VALID_LAST_RESET,
        VALID_VERSION);
  }

  private void assertHasViolation(UserGenAIUsageModel model, String expectedMessage) {
    Set<ConstraintViolation<UserGenAIUsageModel>> violations = validator.validate(model);
    assertTrue(
        violations.stream().anyMatch(v -> v.getMessage().equals(expectedMessage)),
        "Expected violation: " + expectedMessage);
  }

  private void assertNoViolations(UserGenAIUsageModel model) {
    Set<ConstraintViolation<UserGenAIUsageModel>> violations = validator.validate(model);
    assertTrue(violations.isEmpty(), "Expected no violations but got: " + violations);
  }

  @Test
  void model_whenAllFieldsValid_shouldPassValidation() {
    assertNoViolations(buildValidModel());
  }

  @ParameterizedTest
  @NullAndEmptySource
  @ValueSource(strings = {"   "})
  void model_whenUserIdIsInvalid_shouldFailValidation(String userId) {
    UserGenAIUsageModel model = buildValidModel();
    model.setUserId(userId);
    assertHasViolation(model, "User ID cannot be empty");
  }

  @Test
  void model_whenRequestCountIsZero_shouldPassValidation() {
    UserGenAIUsageModel model = buildValidModel();
    model.setRequestCount(0);
    assertNoViolations(model);
  }

  @Test
  void model_whenRequestCountIsPositive_shouldPassValidation() {
    UserGenAIUsageModel model = buildValidModel();
    model.setRequestCount(5);
    assertNoViolations(model);
  }

  @Test
  void model_whenRequestCountIsNegative_shouldFailValidation() {
    UserGenAIUsageModel model = buildValidModel();
    model.setRequestCount(-1);
    assertHasViolation(model, "Request count cannot be negative");
  }

  @Test
  void model_whenMonthlyLimitIsZero_shouldPassValidation() {
    UserGenAIUsageModel model = buildValidModel();
    model.setMonthlyLimit(0);
    assertNoViolations(model);
  }

  @Test
  void model_whenMonthlyLimitIsPositive_shouldPassValidation() {
    UserGenAIUsageModel model = buildValidModel();
    model.setMonthlyLimit(100);
    assertNoViolations(model);
  }

  @Test
  void model_whenMonthlyLimitIsNegative_shouldFailValidation() {
    UserGenAIUsageModel model = buildValidModel();
    model.setMonthlyLimit(-1);
    assertHasViolation(model, "Monthly request limit cannot be negative");
  }

  @Test
  void model_whenLastResetIsNull_shouldFailValidation() {
    UserGenAIUsageModel model = buildValidModel();
    model.setLastReset(null);
    assertHasViolation(model, "Last reset timestamp cannot be null");
  }

  @Test
  void model_whenLastResetIsInThePast_shouldPassValidation() {
    UserGenAIUsageModel model = buildValidModel();
    model.setLastReset(LocalDateTime.now().minusDays(1));
    assertNoViolations(model);
  }

  @Test
  void model_whenLastResetIsNow_shouldPassValidation() {
    UserGenAIUsageModel model = buildValidModel();
    model.setLastReset(LocalDateTime.now());
    assertNoViolations(model);
  }

  @Test
  void constructor_whenUsingThreeArg_shouldSetFieldsCorrectly() {
    UserGenAIUsageModel model =
        new UserGenAIUsageModel(VALID_USER_ID, VALID_MONTHLY_LIMIT, VALID_LAST_RESET);

    assertEquals(VALID_USER_ID, model.getUserId());
    assertEquals(VALID_MONTHLY_LIMIT, model.getMonthlyLimit());
    assertEquals(VALID_LAST_RESET, model.getLastReset());
    assertEquals(0, model.getRequestCount());
    assertNull(model.getId());
  }
}
