name: Java Formatting Check

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ "main" , "dev"]
  pull_request:

jobs:
  spotless-check:
    name: 'Check Formatting (Spotless)'
    runs-on: ubuntu-latest

    steps:
      - name: 'Clone Code'
        uses: actions/checkout@v4

      - name: 'Setup Java JDK'
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 'Grant Execute Permission to Gradlew'
        run: chmod +x gradlew

      - name: 'Run Spotless Check'
        run: ./gradlew spotlessCheck